workflows:
  ios-workflow:
    name: Build iOS App
    environment:
      xcode: latest
    scripts:
      - name: Install Dependencies
        script: pod install
      - name: Build iOS App
        script: xcodebuild -workspace MyApp.xcworkspace -scheme MyApp -sdk iphoneos -configuration Release archive -archivePath $HOME/build/MyApp.xcarchive
      - name: Export IPA
        script: xcodebuild -exportArchive -archivePath $HOME/build/MyApp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $HOME/build/ipa
